### ISSUE TITLE
License of the source code

### ISSUE THREAD

**Issue by Trilarion** [leurqum/Rtype#16]
Hi,

I could not find any information about the license of the source code. Is it under GPL, MIT or something similar?

Kind regards

**Comment by ThierryBerger** [comment]
It was a student's project, it's quite difficult to reach out to all members now, sorry about that, the licence will probably stay undefined.

(for future reference, I'm fine with changing it in any licence, I won't reuse the code, and don't mind other people using it, but I won't offer support or anything else).

To be noted, I **don't** have the rights to take it down if need be.

**Comment by Trilarion** [comment]
Thanks for the info. That's fine. It means that all rights are reserved except for those by the Github TOS which means the code can be hosted and forked and seen here.
