### ISSUE TITLE
Convertion

### ISSUE THREAD

**Issue by morosa** [leurqum/Rtype#7]
Dans RtypeClient/Network.cpp
j ai un pitit probleme de convertion des std::string en char[50] qui doivent remplire les struct
vu que le compilo windows aime pas strcpy ... bref

**Comment by ThierryBerger** [comment]
tu peux utiliser memcpy, avec le .data() ou .c_str() de la string je pense :+1:

**Comment by ThierryBerger** [comment]
et.. sur linux ca ne marche pas non plus, si tu n'inclue pas 

``` cxx
#include <stdio.h>
#include <string.h>
```

EDIT: ca compile avec

``` cpp
#include <string.h>
```
