### ISSUE TITLE
TCP/UDP

### ISSUE THREAD

**Issue by marchesM** [leurqum/Rtype#9]
Coucou !
On utilise des sockets udp et / ou tcp.
Thierry, peux tu me dire ou on utilise de l'udp et ou on utilise du tcp ?

thx, sinon pour le moment j'ai qqs soucis avec mes socks en udp.

**Comment by ThierryBerger** [comment]
j'sais pas moi j'fais du graphisme :smile_cat: 

m'enfin en gros UDP c'est pour : 
- le monde de jeu (du serveur vers le client)
- les commandes clients->serveur pour le jeu (genre up/down/.../fire)

Le reste ca serait du TCP . Y'a ptet des exceptions, mais c'est pas du tout ma partie, alors je sais pas trop :walking:
